services:
  helm-portal:
    hostname: helm-portal
    container_name: helm-portal
    build: 
      platforms:
          - linux/arm64
      context: src
      dockerfile: Dockerfile
      
    environment:
      JWT_SECRET_KEY: test-key
    healthcheck:
      test: ["executable", "arg"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    ports:
      - "3030:3000"
 