version: '3'

tasks:

  dev:
    desc: start air go
    dir: src
    cmds:
    - air

  build:
    desc: Build Docker image
    cmds:
    - docker compose build --push

  run:
    desc: Run the Docker container
    cmds:
    - docker compose up -d

  test-handlers:
    desc: Test handlers
    dir: src/pkg-handlers
    cmds:
    - go test -v .

  test-upload-chart:
    desc: Test upload chart
    dir: src/test
    cmds:
    - http -f POST http://localhost:3030/chart chart@test-chart-0.1.0.tgz

  test-delete-chart:
    desc: Test Delete chart
    dir: src/test
    cmds:
    - http DELETE http://localhost:3030/chart/test-chart version==0.1.0

  test-push-chart:
    desc: Test push chart
    dir: src/test
    cmds:
    - helm push src/test/my-chart-0.1.0.tgz oci://localhost:3030/my-chart --plain-http

default:
  desc: List available tasks
  cmds:
  - task --list
