version: '3'

tasks:

  run-dev:
    desc: start air go
    dir: src
    cmds:
    - air

  build:
    desc: Build Docker image
    cmds:
    - docker compose build --push

  start:
    desc: Run the Docker container
    cmds:
    - docker compose up -d

  stop:
    desc: stop the Docker container
    cmds:
    - docker compose down

  template:
    desc: Template the helmchart
    cmds:
    - helm template helm/ -f helm/values/other/values.yaml > helm/rendered.yaml

  deploy:
    desc: Deploy the helmchart
    cmds:
    - bash update-helm-chart.sh kube-infra

  test-upload-chart:
    desc: Test upload chart
    dir: src/test
    cmds:
    - http -f POST http://localhost:3030/chart chart@test-chart-0.1.0.tgz

  test-delete-chart:
    desc: Test Delete chart
    dir: src/test
    cmds:
    - http DELETE http://localhost:3030/chart/test-chart version==0.1.0

  test-push-chart:
    desc: Test push chart
    dir: src/test
    cmds:
    - helm push  my-chart-0.1.0.tgz oci://localhost:3030/

  test-pull-chart:
    desc: Test pull chart
    dir: src/test
    cmds:
    - helm pull oci://localhost:3030/my-chart --version 0.1.0

default:
  desc: List available tasks
  cmds:
  - task --list
