# Correction pour configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: helm-portal-config   
  namespace: {{ .Release.Namespace }}   
  labels: {{- include "application.labels" . | nindent 4 }}  # 🔧 Labels cohérents
data:
  config.yaml: |-
{{- toYaml .Values.config | nindent 4 }}
