{{/* Create secrets from .env files (convert key=value to key: value) */}}
{{- range $dotenv := .Values.secrets.dotenv }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-{{ $dotenv.name }}
  labels: {{- include "application.labels" $ | nindent 4 }}
  annotations:
    checksum/secret: {{ (tpl ($.Files.Glob $dotenv.path).AsSecrets $ ) | sha256sum }}
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
{{- range $.Files.Lines $dotenv.path }}
  {{- if . }}
  {{ (splitList "=" . | first ) }}: {{ (splitList "=" . | rest | join "=") | trim | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}

{{/* Create secrets from files */}}
{{- range $file := .Values.secrets.files }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-{{ $file.name }}
  labels: {{- include "application.labels" $ | nindent 4 }}
  annotations:
    checksum/secret: {{ (tpl ($.Files.Glob $file.path).AsSecrets $ ) | sha256sum }}
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
{{ ($.Files.Glob $file.path).AsSecrets | indent 2 }}
{{- end }}
