server:
  port: 3030

storage:
  path: "data"

backup:
  gcp:
    bucket: "helm-portal-backup"
    projectID: "dc-consulting-home"
    credentialsFile: "config/dc-consulting-home-pulumi.json"
  # aws:
  #   bucket: "helm-portal-backup"
  #   region: "eu-west-1"
  #   accessKeyID: "YOUR_ACCESS_KEY_ID"
  #   secretAccessKey: "YOUR_SECRET_ACCESS_KEY"

auth:
  enabled: true
  users:
  - username: "admin"
    password: "admin123"
  - username: "dev"
    password: "dev123"

logging:
  level: "info"
  format: "text"
