server:
  port: 3030

storage:
  path: "data"

backup:
  enabled: true
  provider: "azure" # "aws", "gcp", ou "azure"
  azure:
    storageAccount: "myhelmstorage"  # Nom du compte de stockage Azure
    container: "helm-charts-backup"   # Nom du container Azure Blob Storage

logging:
  level: "info"
  format: "text" # ou "json"

# Configuration d'authentification (dans auth.yaml séparé)
auth:
  users:
  - username: "admin"
    password: "admin123"