server:
  port: 3030
  tls:
    certFile: "certs/ca.cert"
    keyFile: "certs/ca.key"
  host: "localhost"

storage:
  path: "data"

auth:
  enabled: true
  users:
  - username: "admin"
    password: "admin123"
  - username: "dev"
    password: "dev123"

helm:
  baseURL: "https://localhost:3030"
  maxChartSize: "100Mi" # optionnel

logging:
  level: "info"
