server:
  port: 3030
  tls:
    certFile: "certs/cert.pem"
    keyFile: "certs/key.pem"
  host: "localhost"

storage:
  path: "charts"

helm:
  baseURL: "https://localhost:3030"
  maxChartSize: "100Mi" # optionnel

logging:
  level: "info"
