persistentVolumesClaims:
- name: helm-portal-data
  accessModes:
  - ReadWriteOnce
  storageClassName: hostpath
  size: 2Gi

ingress:
  host: helm-portal.localhost
  tls:
    enabled: false
  ingressClassName: nginx

env:
- name: ENV
  value: development

config:
  server:
    port: 3030
  storage:
    path: "data"
  backup:
    enabled: false
  logging:
    level: "info"
    format: "text"

secrets:
  files:
  - name: auth
    path: values/home/secrets/auth.yaml